
import React, { useMemo, useState } from 'react';
import { Message, MessageRole } from '../types';
import { IconSparkles, IconGlobe, IconImage, IconCopy, IconCheck, IconRefresh, IconLayout, IconFeather } from './Icons';
import { SourceCard } from './SourceCard';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

interface MessageItemProps {
  message: Message;
  onRegenerate?: (messageId: string) => void;
  onOpenPreview?: (code: string, language: string) => void;
  onSimplify?: (content: string) => void;
}

export const MessageItem: React.FC<MessageItemProps> = ({ message, onRegenerate, onOpenPreview, onSimplify }) => {
  const isUser = message.role === MessageRole.USER;
  const [isCopied, setIsCopied] = useState(false);

  // Unique sources based on URL to prevent duplicates visually
  const uniqueSources = useMemo(() => {
    if (!message.sources) return [];
    const seen = new Set();
    return message.sources.filter(s => {
      if (seen.has(s.uri)) return false;
      seen.add(s.uri);
      return true;
    });
  }, [message.sources]);

  const handleCopy = () => {
    if (message.content) {
      navigator.clipboard.writeText(message.content);
      setIsCopied(true);
      setTimeout(() => setIsCopied(false), 2000);
    }
  };

  if (isUser) {
    return (
      <div className="py-8">
        <div className="text-2xl md:text-3xl font-medium text-textMain font-sans mb-4">
          {message.content}
        </div>
      </div>
    );
  }

  return (
    <div className="py-4 animate-fade-in group">
      {/* Sources Section */}
      {uniqueSources.length > 0 && (
        <div className="mb-6">
          <div className="flex items-center gap-2 text-sm text-secondary font-medium mb-3">
            <IconGlobe className="w-4 h-4 text-primary" />
            <span>Sources</span>
          </div>
          <div className="flex gap-3 overflow-x-auto pb-2 scrollbar-hide -mx-4 px-4 md:mx-0 md:px-0">
            {uniqueSources.map((source, idx) => (
              <SourceCard key={`${source.uri}-${idx}`} source={source} index={idx} />
            ))}
          </div>
        </div>
      )}

      {/* Answer Section */}
      <div className="flex gap-4">
        <div className="flex-shrink-0 mt-1">
           <IconSparkles className="w-6 h-6 text-primary animate-pulse-slow" />
        </div>
        <div className="flex-1 min-w-0">
           <div className="flex items-center gap-2 text-sm text-secondary font-medium mb-2">
            <span>Answer</span>
          </div>
          
          {/* Generated Image */}
          {message.image && (
            <div className="mb-6 mt-2">
                <div className="relative rounded-xl overflow-hidden shadow-2xl border border-border inline-block">
                    <img 
                        src={message.image} 
                        alt="Generated by Gemini" 
                        className="max-w-full h-auto max-h-[512px] w-auto object-contain bg-background"
                    />
                    <div className="absolute bottom-2 right-2 bg-black/60 backdrop-blur-md px-2 py-1 rounded text-[10px] text-white font-medium flex items-center gap-1">
                        <IconImage className="w-3 h-3" />
                        Gemini Image
                    </div>
                </div>
            </div>
          )}

          <div className="prose prose-invert max-w-none text-textMain text-base leading-7">
            <ReactMarkdown 
                remarkPlugins={[remarkGfm]}
                components={{
                    a: ({node, ...props}) => <a {...props} target="_blank" rel="noopener noreferrer" className="text-primary no-underline hover:underline font-medium" />,
                    code: ({className, children, ...props}) => {
                        const match = /language-(\w+)/.exec(className || '');
                        const language = match ? match[1] : '';
                        const codeContent = String(children).replace(/\n$/, '');
                        const isInline = !match; // If no language class, assume inline

                        if (isInline) {
                             return <code className="bg-highlight px-1.5 py-0.5 rounded text-sm font-mono text-textMain" {...props}>{children}</code>;
                        }

                        return (
                             <div className="my-4 rounded-lg border border-border overflow-hidden bg-surface">
                                <div className="flex items-center justify-between px-3 py-2 bg-highlight border-b border-border">
                                    <span className="text-xs font-medium text-secondary uppercase">{language || 'Code'}</span>
                                    <div className="flex items-center gap-2">
                                        {onOpenPreview && (
                                            <button 
                                                onClick={() => onOpenPreview(codeContent, language)}
                                                className="flex items-center gap-1 text-xs text-primary hover:text-primary/80 transition-colors"
                                            >
                                                <IconLayout className="w-3 h-3" />
                                                <span className="hidden sm:inline">Open Preview</span>
                                            </button>
                                        )}
                                        <button 
                                            onClick={() => {
                                                navigator.clipboard.writeText(codeContent);
                                                // Simple visual feedback could go here, handled by parent usually
                                            }}
                                            className="text-xs text-secondary hover:text-textMain"
                                        >
                                            Copy
                                        </button>
                                    </div>
                                </div>
                                <div className="p-4 overflow-x-auto">
                                    <code className={`text-sm font-mono ${className} text-textMain`} {...props}>
                                        {children}
                                    </code>
                                </div>
                             </div>
                        );
                    }
                }}
            >
              {message.content}
            </ReactMarkdown>
            {message.isStreaming && (
                <span className="inline-block w-2 h-4 ml-1 bg-primary align-middle animate-pulse" />
            )}
          </div>

          {/* Action Buttons */}
          {!message.isStreaming && (
            <div className="mt-3 flex items-center gap-3 opacity-0 group-hover:opacity-100 transition-opacity duration-200">
               {onRegenerate && (
                   <button
                     onClick={() => onRegenerate(message.id)}
                     className="flex items-center gap-1.5 text-xs text-secondary hover:text-primary transition-colors p-1 rounded"
                     title="Regenerate response"
                   >
                     <IconRefresh className="w-3.5 h-3.5" />
                     <span>Regenerate</span>
                   </button>
               )}
               <button 
                 onClick={handleCopy}
                 className="flex items-center gap-1.5 text-xs text-secondary hover:text-primary transition-colors p-1 rounded"
                 title="Copy to clipboard"
               >
                 {isCopied ? <IconCheck className="w-3.5 h-3.5" /> : <IconCopy className="w-3.5 h-3.5" />}
                 <span>{isCopied ? 'Copied' : 'Copy'}</span>
               </button>
               
               {onSimplify && (
                   <button
                     onClick={() => onSimplify(message.content)}
                     className="flex items-center gap-1.5 text-xs text-secondary hover:text-primary transition-colors p-1 rounded"
                     title="Explain simply"
                   >
                     <IconFeather className="w-3.5 h-3.5" />
                     <span>Simplify</span>
                   </button>
               )}
            </div>
          )}
        </div>
      </div>
      
      {/* Divider */}
      <div className="h-px bg-border w-full mt-8" />
    </div>
  );
};
